[project]
name = "myvoice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "faster-whisper>=1.2.1",
    "langsmith[openai-agents]>=0.12.4",
    "metaphone>=0.6",
    "numpy>=2.2,<2.3",
    "onnxruntime>=1.29.0",
    "openai-agents>=0.22.1",
    "openwakeword>=0.6.0,<0.7",
    "playwright>=1.62.0",
    "python-dotenv>=1.2.3",
    "rapidfuzz>=3.14.6",
    "sentence-transformers>=6.0.1",
    "silero-vad>=6.2.1",
    "spotipy>=2.26.0",
    "torch",
    "torchaudio",
]

[project.scripts]
myvoice = "myvoice.main:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cpu" }
torchaudio = { index = "pytorch-cpu" }
